#!/bin/sh

# Path to the file where the port will be stored
PORT_FILE="$SNAP_DATA/dcgm_port"

# Create the file with a default port if it doesn't exist
if [ ! -f "$PORT_FILE" ]; then
  echo "5555" > "$PORT_FILE"
  echo "Created dcgm_port file with default port 5555."
else
  echo "dcgm_port file already exists."
fi